apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-simple-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver-simple-app
  template:
    metadata:
      labels:
        app: webserver-simple-app-v10
    spec:
      containers:
        - name: webserver-simple-container
          image: python:3
          command:
            - python
            - -m
            - http.server
          ports:
            - containerPort: 8000
