apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-simple-deployment-v2
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver-simple-app
  template:
    metadata:
      labels:
        app: webserver-simple-app
    spec:
      containers:
        - name: webserver-simple-container
          image: nginx:latest
          ports:
            - containerPort: 80
