apiVersion: v1
kind: Service
metadata:
  name: web-app
  labels:
        app: webserver-simple-app
spec:
  type: NodePort
  selector:
    app: webserver-simple-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32222
